services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      
