version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do container para a porta 3000 do host
    environment:
      NODE_ENV: development
    volumes:
      - .:/app  # Sincroniza o código local com o container (útil para desenvolvimento)