services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      URL_DATABASE: ${URL_DATABASE}  # Referencia a variável de ambiente
      JWT_SECRET: ${JWT_SECRET}      # Referencia a variável de ambiente
      PORT: 8080
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5