name: Release Production Pipeline

on:
  push:
    tags:
      - 'rel-*'  # Aciona o workflow quando uma tag no formato rel-X.Y é criada

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Passo 3: Instalar pnpm globalmente
      - name: Install pnpm
        run: npm install -g pnpm

      # Passo 4: Instalar dependências
      - name: Install dependencies
        run: pnpm install
        working-directory: ./Backend

      # Passo 5: Executar análise estática de código (ESLint)
      - name: Run ESLint
        run: pnpm lint
        working-directory: ./Backend

      # Passo 6: Executar testes unitários
      - name: Run unit tests
        run: pnpm test
        working-directory: ./Backend

      # Passo 7: Fazer login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Passo 8: Buildar a imagem Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sybank-backend:${{ github.ref_name }} ./Backend

      # Passo 9: Publicar a imagem no Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sybank-backend:${{ github.ref_name }}